### ISSUE TITLE
Derastering _some_ datasets next to the antemeridian never terminate

### ISSUE THREAD

**Issue by JayKickliter** [nmandery/rasterh3#6]
I've created a minimal example here https://github.com/JayKickliter/deraster

Derastering the SRTM in the above example seems to never terminate. Others SRTMs along the antimeridian fail to terminate when given a specific resolution, but will terminate fairly quickly if derastering at their "natural" resolution. All other 26,000ish SRTM files deraster fine no matter what resolution I specify.

**Comment by nmandery** [comment]
Thank you for the report and the example.

It seems this happens when encountering a tile which exceeds -180.0...180.0:

```
[/home/nicodev/CLionProjects/h3o-ndarray/src/array.rs:323:5] window_box = Rect {
    min: Coord {
        x: -180.00041666666667,
        y: -19.083750000000002,
    },
    max: Coord {
        x: -179.91708333333332,
        y: -18.999583333333334,
    },
}
```

When compiling in debug mode a `debug_assert` in h3o is triggered:

```
thread 'main' panicked at /home/nicodev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/h3o-0.5.1/src/geom/geometry/polygon.rs:322:17:
cell index 8b9b44789032fff in polygon
```

There is also a new, maybe related, issue in h3o where the same debug_assert is triggered: https://github.com/HydroniumLabs/h3o/issues/23

Anyways it would be good to split the tiles crossing the antimeridian into two parts within this crate and handle those individually. I guess I need a few days before I can find the time to try to fix this.

**Comment by grim7reaper** [comment]
There is some code trying to handle shapes crossing antimeridian, but it isn't perfect (I recently fixed a bug recently on it, reported by @JayKickliter as well ^^).
If you manage to extract the shape triggering the issue I can try to reproduce it on my end and see it if can be fixed.

But keep in mind that the current algorithm, an optimized version of the one used in H3, [has its own limitations](https://github.com/uber/h3-js/issues/24#issuecomment-431893796)

> The current H3 polyfill algorithm can't deal with polygon segments of greater than 180 degrees longitude.

This may be the issue here (to be confirmed once we have extracted the shape that trip up the algorithm)

---

H3 now have a new experimental polyfill algorithm, that I also plan to implement when I get the bandwidth, but I'm not sure it lift those limitations anyway.
As @nmandery  said, the safest approach is to cut those polygon in two.

Still interested to have a look though, in case I can find a way to handle those.

**Comment by JayKickliter** [comment]
I suspected the issue was related to the upstream h3o bug I reported but noticed that rasterh3 pulled in the latest h3o fix. I don't know why I failed to mention that or test in debug mode.

**Comment by nmandery** [comment]
@JayKickliter Could you please test the fix in #7  and check if this fixes the issue for you? Thank you

**Comment by JayKickliter** [comment]
I dropped the ball on monitoring my GitHub notifications. Thank you so much for the fix. I've confirmed this fixes the issue.

**Comment by nmandery** [comment]
No worries - and thank you for the confirmation.
